# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

LINKEDIN_APPID: 77yaxcb4npqwdp
LINKEDIN_KEY: RMGOC3eG86umFW2S

development:
  secret_key_base: ed373be4f1266ba768ec5a6ab78949bb8ecbae66912d94f34975f13d1bcd4c20b685da3ce6069b6eb3410b492bfc441beb18407d0f5f5cc1066ce15e941ca843

test:
  secret_key_base: ab6739e280c659b335419e049f56994c60d7f510f91088987d864313b0c45cc68a68042be09b05cd2bf8ba33600f6b3a189d71ff85b161519869bf7bdd5108aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
