# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af53f06df81826730553820137d917477b801e1c79ca78a882aecf1f0df898f5ad63101536a77eb5ffdb2640c168582d66b630becd7faf5af5fa1d01d351b619

test:
  secret_key_base: f17fc375fabedaf66ed7678d7a9e334b54fff425086a1dcbfeab89066401a52c21fbda1182b26f81addbbfcd529ff74ef18522f85f04419c1c6a4557927edf48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
