# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab9c4870923e3f487a502e787f4662fc438cd4655b3e900f1d48ac57dd55e2d40d5ceba201c640827d46e261f9cd6724c5f341fee182fc62601809a01ab27086

test:
  secret_key_base: c471f27d31b256d52c66d4f209113213de54e75f0062902f8c551b3acbf5efcd5ecb4accbd9f9b839ed91ba37a078a2cb73e142f7d111759bd27dfa264b4ffb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
